# Generated by Django 3.2.13 on 2022-05-06 13:04

from django.db import migrations, models
import shopvisit.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopvisit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True, validators=[shopvisit.models.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
